name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # If you have Dockerfile in the root directory
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/arm64/v8 -t roosteradmin/rooster-client:arm64 .

      # Tag the built image for arm64 architecture
      - name: Tag Docker Image
        run: docker tag roosteradmin/rooster-client:arm64 roosteradmin/rooster-client:arm64

      # Login to Docker Hub and push the arm64 tagged image
      - name: Login to Docker Hub and Push Image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push roosteradmin/rooster-client:arm64
